name: 📦 Release

on:
  push:
    tags:
      - v*

env:
  CIBW_PROJECT_REQUIRES_PYTHON: ">=3.10,<3.13"

jobs:
  make_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-sdist
          path: dist/*.tar.gz

  make_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - {os: macos-13,      arch: x86_64,  build: "*",             version: "a"}
          - {os: macos-14,      arch: arm64,   build: "*",             version: "b"}
          - {os: windows-2022,  arch: AMD64,   build: "*",             version: "c"}
          - {os: ubuntu-latest, arch: x86_64,  build: "*",             version: "d"}
          - {os: ubuntu-latest, arch: aarch64, build: "*0-manylinux*", version: "e"}
          - {os: ubuntu-latest, arch: aarch64, build: "*1-manylinux*", version: "f"}
          - {os: ubuntu-latest, arch: aarch64, build: "*2-manylinux*", version: "g"}
          - {os: ubuntu-latest, arch: aarch64, build: "*0-musllinux*", version: "h"}
          - {os: ubuntu-latest, arch: aarch64, build: "*1-musllinux*", version: "i"}
          - {os: ubuntu-latest, arch: aarch64, build: "*2-musllinux*", version: "j"}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
        if: matrix.os == 'ubuntu-latest'
      - name: Build wheels
        run: pipx run cibuildwheel==2.19.1
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_BUILD: ${{ matrix.build }}
      - uses: actions/upload-artifact@v4
        with:
          name: artifact-wheels-${{ matrix.os }}-${{ matrix.arch }}-${{ matrix.version }}
          path: wheelhouse/*.whl

  upload_all:
    needs: [make_wheels, make_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pandas-plink
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: artifact-*
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
